# Generated by Django 4.2 on 2024-02-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws_app', '0002_cloudservice_created_at_cloudservice_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='databasespecifications',
            name='instance_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='databasespecifications',
            name='instance_type',
            field=models.CharField(default='No type provided.', max_length=50),
        ),
        migrations.AddField(
            model_name='databasespecifications',
            name='volume_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='databasespecifications',
            name='volume_type',
            field=models.CharField(default='No type provided.', max_length=50),
        ),
        migrations.AlterField(
            model_name='databasespecifications',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
