# Generated by Django 4.2 on 2024-02-20 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aws_app', '0003_databasespecifications_instance_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databasespecifications',
            name='max_iops',
        ),
        migrations.RemoveField(
            model_name='databasespecifications',
            name='storage_capacity',
        ),
        migrations.RemoveField(
            model_name='databasespecifications',
            name='volume_price',
        ),
        migrations.RemoveField(
            model_name='databasespecifications',
            name='volume_type',
        ),
        migrations.AddField(
            model_name='databasespecifications',
            name='instance_sku',
            field=models.CharField(default='No SKU provided.', max_length=100),
        ),
        migrations.AlterField(
            model_name='databasespecifications',
            name='cloud_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='database_instances', to='aws_app.cloudservice'),
        ),
        migrations.CreateModel(
            name='DatabaseStorageVolume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume_type', models.CharField(default='No type provided.', max_length=50)),
                ('volume_sku', models.CharField(default='No SKU provided.', max_length=100)),
                ('storage_capacity', models.CharField(max_length=50)),
                ('max_iops', models.IntegerField(blank=True, null=True)),
                ('volume_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_volumes', to='aws_app.databasespecifications')),
            ],
        ),
    ]
