# Generated by Django 4.2 on 2024-02-27 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws_app', '0005_alter_computespecifications_cloud_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='databasestoragevolume',
            name='description',
            field=models.TextField(default='No description provided.'),
        ),
        migrations.AlterField(
            model_name='databasestoragevolume',
            name='storage_capacity',
            field=models.CharField(default='Inf', max_length=50),
        ),
    ]
