# Generated by Django 4.2 on 2024-02-27 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aws_app', '0006_databasestoragevolume_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databasestoragevolume',
            name='instance',
        ),
    ]
