# Generated by Django 4.2 on 2024-02-27 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws_app', '0008_alter_databasestoragevolume_volume_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='databasespecifications',
            name='cpu',
            field=models.CharField(default='No cpu provided.', max_length=50),
        ),
        migrations.AddField(
            model_name='databasespecifications',
            name='description',
            field=models.TextField(default='No description provided.'),
        ),
        migrations.AddField(
            model_name='databasespecifications',
            name='memory',
            field=models.CharField(default='No memory provided.', max_length=50),
        ),
        migrations.AddField(
            model_name='databasespecifications',
            name='network_performance',
            field=models.CharField(default='No network provided.', max_length=50),
        ),
        migrations.AddField(
            model_name='databasespecifications',
            name='product',
            field=models.CharField(default='No product provided.', max_length=50),
        ),
    ]
