# Generated by Django 4.2 on 2024-02-28 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws_app', '0011_remove_storagespecifications_cloud_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagespecifications',
            name='service_code',
            field=models.CharField(default='No code provided.', max_length=50),
        ),
    ]
