# Generated by Django 4.2 on 2024-02-28 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws_app', '0012_storagespecifications_service_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagespecifications',
            name='storage_class',
            field=models.CharField(default='No class provided.', max_length=50),
        ),
    ]
