# Generated by Django 4.2 on 2024-02-28 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws_app', '0014_rename_instance_price_storagespecifications_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storagespecifications',
            name='price',
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=10),
        ),
    ]
