# Generated by Django 5.0.2 on 2024-02-27 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CloudService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ComputeSpecifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(default='SKU not provided', max_length=100, unique=True)),
                ('instance_type', models.CharField(default='No type provided.', max_length=50)),
                ('operating_system', models.CharField(default='Ubuntu Pro', max_length=50)),
                ('cpu', models.CharField(max_length=50)),
                ('memory', models.CharField(max_length=50)),
                ('network_performance', models.CharField(default='No network provided.', max_length=50)),
                ('tenancy', models.CharField(default='No description provided.', max_length=50)),
                ('description', models.TextField(default='No description provided.')),
                ('price_per_unit', models.DecimalField(decimal_places=7, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('cloud_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compute_specs', to='databaseServer.cloudservice')),
            ],
        ),
        migrations.CreateModel(
            name='DatabaseSpecifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_engine', models.CharField(max_length=50)),
                ('storage_capacity', models.CharField(max_length=50)),
                ('max_iops', models.IntegerField()),
                ('cloud_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='database_specs', to='databaseServer.cloudservice')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkingSpecifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bandwidth', models.CharField(max_length=50)),
                ('technology', models.CharField(max_length=50)),
                ('cloud_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='networking_specs', to='databaseServer.cloudservice')),
            ],
        ),
        migrations.AddField(
            model_name='cloudservice',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='databaseServer.provider'),
        ),
        migrations.CreateModel(
            name='StorageSpecifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_class', models.CharField(max_length=50)),
                ('redundancy', models.CharField(max_length=50)),
                ('durability', models.CharField(max_length=50)),
                ('cloud_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storage_specs', to='databaseServer.cloudservice')),
            ],
        ),
    ]
