# Generated by Django 5.0.2 on 2024-02-27 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseServer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='computespecifications',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='databasespecifications',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='networkingspecifications',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='storagespecifications',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
