# Generated by Django 5.0.2 on 2024-02-27 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseServer', '0002_computespecifications_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computespecifications',
            name='location',
            field=models.CharField(default='No location provided', max_length=50),
        ),
        migrations.AddField(
            model_name='databasespecifications',
            name='location',
            field=models.CharField(default='No location provided', max_length=50),
        ),
        migrations.AddField(
            model_name='networkingspecifications',
            name='location',
            field=models.CharField(default='No location provided', max_length=50),
        ),
        migrations.AddField(
            model_name='storagespecifications',
            name='location',
            field=models.CharField(default='No location provided', max_length=50),
        ),
    ]
