# Generated by Django 5.0.2 on 2024-02-27 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseServer', '0003_computespecifications_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computespecifications',
            name='location',
        ),
        migrations.RemoveField(
            model_name='databasespecifications',
            name='location',
        ),
        migrations.RemoveField(
            model_name='networkingspecifications',
            name='location',
        ),
        migrations.RemoveField(
            model_name='storagespecifications',
            name='location',
        ),
        migrations.AddField(
            model_name='computespecifications',
            name='region',
            field=models.CharField(default='No region provided', max_length=50),
        ),
        migrations.AddField(
            model_name='databasespecifications',
            name='region',
            field=models.CharField(default='No region provided', max_length=50),
        ),
        migrations.AddField(
            model_name='networkingspecifications',
            name='region',
            field=models.CharField(default='No region provided', max_length=50),
        ),
        migrations.AddField(
            model_name='storagespecifications',
            name='region',
            field=models.CharField(default='No region provided', max_length=50),
        ),
    ]
