# Generated by Django 5.0.2 on 2024-02-27 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseServer', '0004_remove_computespecifications_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storagespecifications',
            old_name='durability',
            new_name='sku',
        ),
        migrations.RenameField(
            model_name='storagespecifications',
            old_name='redundancy',
            new_name='unit_of_measure',
        ),
        migrations.RenameField(
            model_name='storagespecifications',
            old_name='storage_class',
            new_name='unit_price',
        ),
    ]
