# Generated by Django 5.0.2 on 2024-02-27 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseServer', '0005_rename_durability_storagespecifications_sku_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computespecifications',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='databaseServer.provider'),
        ),
        migrations.AddField(
            model_name='databasespecifications',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='databaseServer.provider'),
        ),
        migrations.AddField(
            model_name='networkingspecifications',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='databaseServer.provider'),
        ),
        migrations.AddField(
            model_name='storagespecifications',
            name='provider',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='databaseServer.provider'),
        ),
        migrations.AlterField(
            model_name='cloudservice',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseServer.provider'),
        ),
        migrations.AlterField(
            model_name='networkingspecifications',
            name='cloud_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseServer.cloudservice'),
        ),
    ]
