# Generated by Django 5.0.2 on 2024-02-27 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseServer', '0007_rename_bandwidth_networkingspecifications_sku_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='databasespecifications',
            old_name='db_engine',
            new_name='data_type',
        ),
        migrations.RenameField(
            model_name='databasespecifications',
            old_name='storage_capacity',
            new_name='sku',
        ),
        migrations.RenameField(
            model_name='storagespecifications',
            old_name='unit_of_measure',
            new_name='unit_of_storage',
        ),
        migrations.RemoveField(
            model_name='databasespecifications',
            name='max_iops',
        ),
        migrations.AddField(
            model_name='databasespecifications',
            name='unit_of_storage',
            field=models.CharField(default='0.0', max_length=50),
        ),
        migrations.AddField(
            model_name='databasespecifications',
            name='unit_price',
            field=models.CharField(default='0.0', max_length=50),
        ),
    ]
