# Generated by Django 5.0.2 on 2024-02-29 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseServer', '0009_remove_computespecifications_price_per_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagespecifications',
            name='description',
            field=models.TextField(default='No description provided.'),
        ),
        migrations.AddField(
            model_name='storagespecifications',
            name='max_iops',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storagespecifications',
            name='storage_capacity',
            field=models.CharField(default='Inf', max_length=50),
        ),
        migrations.AddField(
            model_name='storagespecifications',
            name='volume_sku',
            field=models.CharField(default='No SKU provided.', max_length=100),
        ),
        migrations.AddField(
            model_name='storagespecifications',
            name='volume_type',
            field=models.CharField(default='No type provided.', max_length=50),
        ),
    ]
