# Generated by Django 5.0.2 on 2024-03-24 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseServer', '0010_computespecifications_price_monthly_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computespecifications',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='databasespecifications',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='networkingspecifications',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storagespecifications',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
