# Generated by Django 5.0.2 on 2024-02-29 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseServer', '0011_remove_storagespecifications_volume_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storagespecifications',
            name='description',
        ),
        migrations.RemoveField(
            model_name='storagespecifications',
            name='max_iops',
        ),
        migrations.RemoveField(
            model_name='storagespecifications',
            name='storage_capacity',
        ),
        migrations.RemoveField(
            model_name='storagespecifications',
            name='volume_type',
        ),
        migrations.AddField(
            model_name='databasespecifications',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='databasespecifications',
            name='storage_capacity',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='databasespecifications',
            name='volume_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
