# Generated by Django 5.0.2 on 2024-02-29 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseServer', '0012_remove_storagespecifications_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='databasespecifications',
            name='product',
            field=models.CharField(default='No product provided.', max_length=50),
        ),
    ]
