# Generated by Django 5.0.2 on 2024-02-29 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseServer', '0013_databasespecifications_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='databasespecifications',
            name='cpu',
            field=models.CharField(default='No cpu provided.', max_length=50),
        ),
        migrations.AddField(
            model_name='databasespecifications',
            name='db_engine',
            field=models.CharField(default='No engine used', max_length=50),
        ),
        migrations.AddField(
            model_name='databasespecifications',
            name='instance_type',
            field=models.CharField(default='No type provided.', max_length=50),
        ),
        migrations.AddField(
            model_name='databasespecifications',
            name='memory',
            field=models.CharField(default='No memory provided.', max_length=50),
        ),
        migrations.AddField(
            model_name='databasespecifications',
            name='network_performance',
            field=models.CharField(default='No network provided.', max_length=50),
        ),
    ]
