# Generated by Django 5.0.2 on 2024-03-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseServer', '0014_alter_computespecifications_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computespecifications',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='databasespecifications',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='networkingspecifications',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='storagespecifications',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
