# Generated by Django 5.0.2 on 2024-03-04 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('databaseServer', '0010_computespecifications_price_monthly_and_more'),
        ('databaseServer', '0015_storagespecifications_description_and_more'),
    ]

    operations = [
    ]
