# Generated by Django 5.0.2 on 2024-03-25 19:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseServer', '0015_alter_computespecifications_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computespecifications',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='databasespecifications',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='networkingspecifications',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='storagespecifications',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
