# Generated by Django 5.0.3 on 2024-03-26 02:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('databaseServer', '0016_merge_20240303_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='computespecifications',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='databasespecifications',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='networkingspecifications',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='storagespecifications',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='databasespecifications',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='databaseServer.provider'),
        ),
    ]
